#include "Ship/NavalCombatComponent.h"
#include "EngineUtils.h"
#include "GameFramework/Actor.h"
UNavalCombatComponent::UNavalCombatComponent(){PrimaryComponentTick.bCanEverTick=true;}
void UNavalCombatComponent::BeginPlay(){Super::BeginPlay();CurrentHull=MaxHull;}
void UNavalCombatComponent::TickComponent(float D,ELevelTick T,FActorComponentTickFunction* F){Super::TickComponent(D,T,F);PortReload=FMath::Max(0.f,PortReload-D);StarboardReload=FMath::Max(0.f,StarboardReload-D);SetComponentTickEnabled(PortReload>0.f||StarboardReload>0.f);}
float UNavalCombatComponent::GetReloadRemaining(ENavalBroadside S) const{return S==ENavalBroadside::Port?PortReload:StarboardReload;}
AActor* UNavalCombatComponent::FindBroadsideTarget(ENavalBroadside Side) const{const AActor* Owner=GetOwner();UWorld* W=GetWorld();if(!Owner||!W)return nullptr;const FVector O=Owner->GetActorLocation(),R=Owner->GetActorRightVector();AActor* Best=nullptr;float BestSq=FMath::Square(BroadsideRange);for(TActorIterator<AActor> It(W);It;++It){AActor* C=*It;if(!C||C==Owner)continue;UNavalCombatComponent* Combat=C->FindComponentByClass<UNavalCombatComponent>();if(!Combat||Combat->IsSunk()||Combat->bPlayerAligned==bPlayerAligned)continue;const FVector Delta=C->GetActorLocation()-O;const float Dot=FVector::DotProduct(Delta.GetSafeNormal2D(),R);if((Side==ENavalBroadside::Port&&Dot>-0.25f)||(Side==ENavalBroadside::Starboard&&Dot<0.25f))continue;const float Sq=Delta.SizeSquared();if(Sq<BestSq){BestSq=Sq;Best=C;}}return Best;}
bool UNavalCombatComponent::FireBroadside(ENavalBroadside Side){if(IsSunk())return false;float& Reload=Side==ENavalBroadside::Port?PortReload:StarboardReload;if(Reload>0.f)return false;AActor* Target=FindBroadsideTarget(Side);if(!Target)return false;UNavalCombatComponent* Combat=Target->FindComponentByClass<UNavalCombatComponent>();if(!Combat)return false;const float Damage=FMath::Max(1,CannonsPerSide)*FMath::Max(0.f,DamagePerCannon);Combat->ApplyHullDamage(Damage,GetOwner());Reload=ReloadSeconds;SetComponentTickEnabled(true);OnBroadsideFired.Broadcast(Side,CannonsPerSide,Damage);return true;}
void UNavalCombatComponent::ApplyHullDamage(float Damage,AActor*){if(Damage<=0.f||IsSunk())return;CurrentHull=FMath::Clamp(CurrentHull-Damage,0.f,MaxHull);if(IsSunk()&&GetOwner())GetOwner()->SetActorEnableCollision(false);}
