#include "DarkArisenMaterializeStoryCommandlet.h"

#include "AlphaGameplayGameMode.h"
#include "AssetImportTask.h"
#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetToolsModule.h"
#include "Bosses/DravenVossBossCharacter.h"
#include "Bosses/DreamEthanBossCharacter.h"
#include "Bosses/MainStoryHolderBossCharacter.h"
#include "Characters/EthanHarlowCharacter.h"
#include "Components/StaticMeshComponent.h"
#include "Dom/JsonObject.h"
#include "DuelingEnemyCharacter.h"
#include "Ship/HostileNavalShip.h"
#include "Ship/LaLiberacionShip.h"
#include "Engine/StaticMesh.h"
#include "Engine/StaticMeshActor.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "Factories/WorldFactory.h"
#include "FileHelpers.h"
#include "GameFramework/PlayerStart.h"
#include "GameFramework/WorldSettings.h"
#include "HAL/FileManager.h"
#include "Interaction/ExamineDocumentActor.h"
#include "IAssetTools.h"
#include "Misc/EngineVersion.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Modules/ModuleManager.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Story/CreditsPresentationActor.h"
#include "Story/DarkArisenWorldDirector.h"
#include "Story/MainStoryContactActor.h"
#include "Story/MainStoryEvidenceActor.h"
#include "Story/MainStoryLocationTriggerActor.h"
#include "Story/MainStoryMapTransitionActor.h"
#include "Story/NavalEncounterGateActor.h"
#include "Story/MainStoryRouteResolutionActor.h"
#include "Story/MainStoryWarActionActor.h"
#include "UObject/Package.h"

namespace DarkArisenStoryMaterialize
{
static FString Str(const TSharedPtr<FJsonObject>& Object, const TCHAR* Field){FString Value;if(Object.IsValid())Object->TryGetStringField(Field,Value);return Value;}
static FName Name(const TSharedPtr<FJsonObject>& Object,const TCHAR* Field){const FString Value=Str(Object,Field);return Value.IsEmpty()?NAME_None:FName(*Value);}
static bool Bool(const TSharedPtr<FJsonObject>& Object,const TCHAR* Field,bool DefaultValue=false){bool Value=DefaultValue;if(Object.IsValid())Object->TryGetBoolField(Field,Value);return Value;}
static int32 Int(const TSharedPtr<FJsonObject>& Object,const TCHAR* Field){double Value=0.0;return Object.IsValid()&&Object->TryGetNumberField(Field,Value)?FMath::Max(0,FMath::RoundToInt(Value)):0;}
static bool ReadJson(const FString& Path,TSharedPtr<FJsonObject>& Out){FString Text;return FFileHelper::LoadFileToString(Text,*Path)&&FJsonSerializer::Deserialize(TJsonReaderFactory<>::Create(Text),Out)&&Out.IsValid();}
static bool ReadVector(const TArray<TSharedPtr<FJsonValue>>* Values,FVector& Out){if(!Values||Values->Num()!=3)return false;for(const auto& Value:*Values)if(!Value.IsValid()||Value->Type!=EJson::Number)return false;Out=FVector((*Values)[0]->AsNumber(),(*Values)[1]->AsNumber(),(*Values)[2]->AsNumber());return !Out.ContainsNaN();}
static bool ReadAnchor(const TSharedPtr<FJsonObject>& Root,const FString& AnchorName,FVector& Out){const TSharedPtr<FJsonObject>* Anchors=nullptr;if(!Root.IsValid()||!Root->TryGetObjectField(TEXT("anchors"),Anchors)||!Anchors||!Anchors->IsValid())return false;const TArray<TSharedPtr<FJsonValue>>* Values=nullptr;return (*Anchors)->TryGetArrayField(AnchorName,Values)&&ReadVector(Values,Out);}
template<typename T> static T* EnsureActor(UWorld* World,FName StableName,const FVector& Location){if(!World||StableName.IsNone())return nullptr;for(TActorIterator<T> It(World);It;++It){if(It->GetFName()==StableName){It->SetActorLocation(Location);return *It;}}FActorSpawnParameters Spawn;Spawn.Name=StableName;Spawn.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;return World->SpawnActor<T>(T::StaticClass(),Location,FRotator::ZeroRotator,Spawn);}
static UWorld* OpenOrCreateWorld(const FString& MapId){const FString PackageName=TEXT("/Game/Alpha/Maps/")+MapId;const FString ObjectPath=PackageName+TEXT(".")+MapId;if(UWorld* Existing=LoadObject<UWorld>(nullptr,*ObjectPath))return Existing;UPackage* Package=CreatePackage(*PackageName);UWorldFactory* Factory=NewObject<UWorldFactory>();Factory->WorldType=EWorldType::Game;Factory->bCreateWorldPartition=false;Factory->bEnableWorldPartitionStreaming=false;Factory->bInformEngineOfWorld=false;UWorld* World=Cast<UWorld>(Factory->FactoryCreateNew(UWorld::StaticClass(),Package,*MapId,RF_Public|RF_Standalone,nullptr,GWarn));if(World)FAssetRegistryModule::AssetCreated(World);return World;}
static bool SaveWorld(UWorld* World){if(!World)return false;World->MarkPackageDirty();TArray<UPackage*> Packages{World->GetOutermost()};return UEditorLoadingAndSavingUtils::SavePackages(Packages,false);}
static UStaticMesh* ImportGeometry(IAssetTools& AssetTools,const FString& ObjectPath){if(ObjectPath.IsEmpty())return nullptr;if(UStaticMesh* Existing=LoadObject<UStaticMesh>(nullptr,*ObjectPath))return Existing;FString PackagePath,AssetName;if(!ObjectPath.Split(TEXT("."),&PackagePath,&AssetName)||AssetName.IsEmpty())return nullptr;const FString Destination=FPaths::GetPath(PackagePath);TArray<FString> Matches;IFileManager::Get().FindFilesRecursive(Matches,*FPaths::Combine(FPaths::ProjectDir(),TEXT("ContentSource")),*(AssetName+TEXT(".gltf")),true,false,false);if(Matches.Num()!=1)return nullptr;UAssetImportTask* Task=NewObject<UAssetImportTask>();Task->Filename=Matches[0];Task->DestinationPath=Destination;Task->bAutomated=true;Task->bReplaceExisting=true;Task->bSave=true;Task->bAsync=false;TArray<UAssetImportTask*> Tasks{Task};AssetTools.ImportAssetTasks(Tasks);if(UStaticMesh* Imported=LoadObject<UStaticMesh>(nullptr,*ObjectPath))return Imported;for(UObject* ImportedObject:Task->GetObjects())if(UStaticMesh* Candidate=Cast<UStaticMesh>(ImportedObject)){TArray<FAssetRenameData> Rename;Rename.Emplace(TWeakObjectPtr<UObject>(Candidate),Destination,AssetName);if(!AssetTools.RenameAssets(Rename))return nullptr;return LoadObject<UStaticMesh>(nullptr,*ObjectPath);}return nullptr;}
static bool MaterializeGeometry(IAssetTools& AssetTools,UWorld* World,const TSharedPtr<FJsonObject>& Root){const TArray<TSharedPtr<FJsonValue>>* Specs=nullptr;if(Root->TryGetArrayField(TEXT("geometry"),Specs))for(const auto& Value:*Specs){auto Spec=Value.IsValid()?Value->AsObject():nullptr;FVector Location;const FString ActorName=Str(Spec,TEXT("name"));if(ActorName.IsEmpty()||!ReadAnchor(Root,Str(Spec,TEXT("anchor")),Location))return false;UStaticMesh* Mesh=ImportGeometry(AssetTools,Str(Spec,TEXT("objectPath")));AStaticMeshActor* Actor=Mesh?EnsureActor<AStaticMeshActor>(World,FName(*ActorName),Location):nullptr;if(!Actor)return false;Actor->GetStaticMeshComponent()->SetStaticMesh(Mesh);}if(Root->TryGetArrayField(TEXT("physicalGeometry"),Specs)){UStaticMesh* Cube=LoadObject<UStaticMesh>(nullptr,TEXT("/Engine/BasicShapes/Cube.Cube"));if(!Cube)return false;for(const auto& Value:*Specs){auto Spec=Value.IsValid()?Value->AsObject():nullptr;FVector Location,Size;const TArray<TSharedPtr<FJsonValue>>* SizeValues=nullptr;const FString ActorName=Str(Spec,TEXT("name"));if(ActorName.IsEmpty()||!ReadAnchor(Root,Str(Spec,TEXT("anchor")),Location)||!Spec->TryGetArrayField(TEXT("size"),SizeValues)||!ReadVector(SizeValues,Size))return false;AStaticMeshActor* Actor=EnsureActor<AStaticMeshActor>(World,FName(*ActorName),Location);if(!Actor)return false;Actor->GetStaticMeshComponent()->SetStaticMesh(Cube);Actor->SetActorScale3D(Size/100.0);}}return true;}
static EColonialFaction ParseFaction(const FString& Value){if(Value.Equals(TEXT("Albion"),ESearchCase::IgnoreCase))return EColonialFaction::Albion;if(Value.Equals(TEXT("Liberation"),ESearchCase::IgnoreCase))return EColonialFaction::Liberation;if(Value.Equals(TEXT("Crimson"),ESearchCase::IgnoreCase)||Value.Equals(TEXT("CrimsonArmada"),ESearchCase::IgnoreCase))return EColonialFaction::Crimson;return EColonialFaction::Imperial;}
static EWarActionVerb ParseWarVerb(const FString& Value){if(Value.Equals(TEXT("Support"),ESearchCase::IgnoreCase))return EWarActionVerb::Support;if(Value.Equals(TEXT("Liberate"),ESearchCase::IgnoreCase))return EWarActionVerb::Liberate;return EWarActionVerb::Break;}
static AMainStoryHolderBossCharacter* SpawnBoss(UWorld* World,FName NameValue,const FVector& Location,FName BossId){if(BossId==TEXT("boss.dream_ethan"))return EnsureActor<ADreamEthanBossCharacter>(World,NameValue,Location);if(BossId==TEXT("boss.draven_voss"))return EnsureActor<ADravenVossBossCharacter>(World,NameValue,Location);return EnsureActor<AMainStoryHolderBossCharacter>(World,NameValue,Location);}
static bool MaterializeActors(UWorld* World,const TSharedPtr<FJsonObject>& Root){const FString MissionString=Str(Root,TEXT("missionId"));const FName MissionId(*MissionString);const FName RootCheckpoint=Name(Root,TEXT("checkpointId"));const FName RootSpawn=Name(Root,TEXT("spawnId"));const FString RootRegion=Str(Root,TEXT("regionId"));const TArray<TSharedPtr<FJsonValue>>* Specs=nullptr;if(MissionString.IsEmpty()||!Root->TryGetArrayField(TEXT("actors"),Specs))return false;for(const auto& Value:*Specs){auto Spec=Value.IsValid()?Value->AsObject():nullptr;const FString Type=Str(Spec,TEXT("type"));const FString ActorName=Str(Spec,TEXT("name"));FVector Location;if(!Spec.IsValid()||Type.IsEmpty()||ActorName.IsEmpty()||!ReadAnchor(Root,Str(Spec,TEXT("anchor")),Location))return false;const FName StableName(*ActorName);if(Type==TEXT("LocationTrigger")){auto* Actor=EnsureActor<AMainStoryLocationTriggerActor>(World,StableName,Location);if(!Actor)return false;Actor->MissionId=MissionId;Actor->Action=Str(Spec,TEXT("action"))==TEXT("CompleteMission")?EMainStoryLocationAction::CompleteMission:EMainStoryLocationAction::ActivateMission;Actor->CheckpointId=Name(Spec,TEXT("checkpointId"));if(Actor->CheckpointId.IsNone())Actor->CheckpointId=RootCheckpoint;Actor->SpawnId=Name(Spec,TEXT("spawnId"));if(Actor->SpawnId.IsNone())Actor->SpawnId=RootSpawn;}
else if(Type==TEXT("Contact")){auto* Actor=EnsureActor<AMainStoryContactActor>(World,StableName,Location);if(!Actor)return false;Actor->MissionId=MissionId;Actor->ContactId=Name(Spec,TEXT("contactId"));Actor->DialogueId=Name(Spec,TEXT("dialogueId"));Actor->DisplayName=FText::FromString(Str(Spec,TEXT("displayName")));Actor->DialogueText=FText::FromString(Str(Spec,TEXT("text")));Actor->bActivateMissionOnInteraction=Bool(Spec,TEXT("activatesMission"));Actor->bCompleteMissionOnInteraction=Bool(Spec,TEXT("completesMission"));Actor->CheckpointId=Name(Spec,TEXT("checkpointId"));if(Actor->CheckpointId.IsNone())Actor->CheckpointId=RootCheckpoint;Actor->SpawnId=Name(Spec,TEXT("spawnId"));if(Actor->SpawnId.IsNone())Actor->SpawnId=RootSpawn;}
else if(Type==TEXT("EthanHarlow")){auto* Actor=EnsureActor<AEthanHarlowCharacter>(World,StableName,Location);if(!Actor)return false;Actor->RuntimeState=Str(Spec,TEXT("state"))==TEXT("Aboard")?EEthanRuntimeState::Aboard:(Str(Spec,TEXT("state"))==TEXT("Rescued")?EEthanRuntimeState::Rescued:EEthanRuntimeState::Captive);}
else if(Type==TEXT("Evidence")){if(Bool(Spec,TEXT("completesMission"))){auto* Actor=EnsureActor<AMainStoryEvidenceActor>(World,StableName,Location);if(!Actor)return false;Actor->MissionId=MissionId;Actor->DocumentTitle=FText::FromString(Str(Spec,TEXT("title")));Actor->DocumentBody=FText::FromString(Str(Spec,TEXT("body")));Actor->CheckpointId=Name(Spec,TEXT("checkpointId"));if(Actor->CheckpointId.IsNone())Actor->CheckpointId=RootCheckpoint;Actor->SpawnId=Name(Spec,TEXT("spawnId"));if(Actor->SpawnId.IsNone())Actor->SpawnId=RootSpawn;Actor->RequiredBossId=Name(Spec,TEXT("requiredBossId"));}else{auto* Actor=EnsureActor<AExamineDocumentActor>(World,StableName,Location);if(!Actor)return false;Actor->DocumentTitle=FText::FromString(Str(Spec,TEXT("title")));Actor->DocumentBody=FText::FromString(Str(Spec,TEXT("body")));}}
else if(Type==TEXT("RouteResolution")){auto* Actor=EnsureActor<AMainStoryRouteResolutionActor>(World,StableName,Location);if(!Actor)return false;Actor->MissionId=MissionId;Actor->OutcomeKey=Name(Spec,TEXT("outcomeKey"));Actor->OutcomeValue=Name(Spec,TEXT("outcomeValue"));Actor->InteractionLabel=FText::FromString(Str(Spec,TEXT("label")));}
else if(Type==TEXT("WarAction")){auto* Actor=EnsureActor<AMainStoryWarActionActor>(World,StableName,Location);if(!Actor)return false;Actor->MissionId=MissionId;const FString Region=Str(Spec,TEXT("regionId"));Actor->RegionId=FName(*(Region.IsEmpty()?RootRegion:Region));Actor->InitialController=ParseFaction(Str(Spec,TEXT("initialController")));Actor->Verb=ParseWarVerb(Str(Spec,TEXT("verb")));Actor->TargetFaction=ParseFaction(Str(Spec,TEXT("targetFaction")));Actor->ControlDelta=Int(Spec,TEXT("controlDelta"));Actor->LiberationDelta=Int(Spec,TEXT("liberationDelta"));Actor->CrimsonDelta=Int(Spec,TEXT("crimsonDelta"));Actor->OutcomeKey=Name(Spec,TEXT("outcomeKey"));Actor->OutcomeValue=Name(Spec,TEXT("outcomeValue"));Actor->InteractionLabel=FText::FromString(Str(Spec,TEXT("label")));}
else if(Type==TEXT("HolderBoss")){const FName BossId=Name(Spec,TEXT("bossId"));auto* Actor=SpawnBoss(World,StableName,Location,BossId);if(!Actor)return false;Actor->MissionId=MissionId;Actor->BossId=BossId;Actor->OutcomeKey=Name(Spec,TEXT("outcomeKey"));Actor->OutcomeValue=Name(Spec,TEXT("outcomeValue"));Actor->bCompleteMissionOnDefeat=Bool(Spec,TEXT("completesMissionOnDefeat"),true);}
else if(Type==TEXT("DuelingEnemy")){if(!EnsureActor<ADuelingEnemyCharacter>(World,StableName,Location))return false;}else if(Type==TEXT("PlayerShip")){auto* Actor=EnsureActor<ALaLiberacionShip>(World,StableName,Location);if(!Actor)return false;Actor->bStartInCombatHelm=true;}else if(Type==TEXT("NavalEnemy")){if(!EnsureActor<AHostileNavalShip>(World,StableName,Location))return false;}else if(Type==TEXT("NavalEncounterGate")){auto* Actor=EnsureActor<ANavalEncounterGateActor>(World,StableName,Location);if(!Actor)return false;Actor->MissionId=MissionId;Actor->RequiredDefeats=FMath::Max(1,Int(Spec,TEXT("requiredDefeats")));}else{UE_LOG(LogTemp,Error,TEXT("Unknown story actor type %s in %s"),*Type,*MissionString);return false;}}return true;}
static bool MaterializeStoryContract(IAssetTools& AssetTools,const FString& Path,const TMap<FName,FName>& MissionMaps){TSharedPtr<FJsonObject> Root;if(!ReadJson(Path,Root))return false;const FString MissionString=Str(Root,TEXT("missionId"));const FString MapId=Str(Root,TEXT("mapId"));if(MissionString.IsEmpty()||MapId.IsEmpty())return false;UWorld* World=OpenOrCreateWorld(MapId);if(!World)return false;if(AWorldSettings* Settings=World->GetWorldSettings())Settings->DefaultGameMode=AAlphaGameplayGameMode::StaticClass();EnsureActor<ADarkArisenWorldDirector>(World,TEXT("WorldDirector"),FVector::ZeroVector);FVector Entry=FVector::ZeroVector;ReadAnchor(Root,Str(Root,TEXT("entryAnchor")),Entry);EnsureActor<APlayerStart>(World,TEXT("PlayerStart"),Entry+FVector(0,0,120));auto* Transition=EnsureActor<AMainStoryMapTransitionActor>(World,TEXT("StoryMapTransition"),Entry);if(!Transition)return false;Transition->MissionId=FName(*MissionString);const FName NextMission=Name(Root,TEXT("nextMission"));if(!NextMission.IsNone()){if(const FName* NextMap=MissionMaps.Find(NextMission))Transition->NextMap=*NextMap;else return false;}else if(MissionString==TEXT("Main.C10.05.TheWakeAfter"))Transition->NextMap=TEXT("L_Credits");return MaterializeGeometry(AssetTools,World,Root)&&MaterializeActors(World,Root)&&SaveWorld(World);}
static FString BuildCreditsText(const TSharedPtr<FJsonObject>& Authority){FString Text=Str(Authority,TEXT("title"));Text+=TEXT("\n\nA game built in Unreal Engine\n\n");const TArray<TSharedPtr<FJsonValue>>* Technology=nullptr;if(Authority->TryGetArrayField(TEXT("verifiedTechnology"),Technology)&&Technology){Text+=TEXT("VERIFIED TECHNOLOGY\n");for(const auto& Value:*Technology)if(Value.IsValid()&&Value->Type==EJson::String)Text+=Value->AsString()+TEXT("\n");Text+=TEXT("\n");}const TArray<TSharedPtr<FJsonValue>>* Provenance=nullptr;if(Authority->TryGetArrayField(TEXT("generatedSourceProvenance"),Provenance)&&Provenance){Text+=TEXT("SOURCE PROVENANCE\n");for(const auto& Value:*Provenance)if(Value.IsValid()&&Value->Type==EJson::String)Text+=Value->AsString()+TEXT("\n");}Text+=TEXT("\nThank you for playing.\n");return Text;}
static bool MaterializeCredits(){const FString ContractPath=FPaths::Combine(FPaths::ProjectDir(),TEXT("ContentSource/Presentation/Credits/L_Credits.contract.json"));const FString AuthorityPath=FPaths::Combine(FPaths::ProjectDir(),TEXT("ContentSource/Story/Credits/CreditsAuthority.json"));TSharedPtr<FJsonObject> Contract,Authority;if(!ReadJson(ContractPath,Contract)||!ReadJson(AuthorityPath,Authority))return false;const FString MapId=Str(Contract,TEXT("mapId"));if(MapId.IsEmpty())return false;UWorld* World=OpenOrCreateWorld(MapId);if(!World)return false;if(AWorldSettings* Settings=World->GetWorldSettings())Settings->DefaultGameMode=AAlphaGameplayGameMode::StaticClass();auto* Credits=EnsureActor<ACreditsPresentationActor>(World,TEXT("CreditsPresentation"),FVector::ZeroVector);if(!Credits)return false;Credits->RollText=FText::FromString(BuildCreditsText(Authority));const TSharedPtr<FJsonObject>* Input=nullptr;if(Contract->TryGetObjectField(TEXT("input"),Input)&&Input&&Input->IsValid()){double SkipSeconds=8.0;if((*Input)->TryGetNumberField(TEXT("allowSkipAfterSeconds"),SkipSeconds))Credits->AllowSkipAfterSeconds=FMath::Max(0.f,static_cast<float>(SkipSeconds));}return SaveWorld(World);}
}
UDarkArisenMaterializeStoryCommandlet::UDarkArisenMaterializeStoryCommandlet(){IsClient=false;IsServer=false;LogToConsole=true;}
int32 UDarkArisenMaterializeStoryCommandlet::Main(const FString&){if(FEngineVersion::Current().GetMajor()!=5||FEngineVersion::Current().GetMinor()!=8)return 2;IAssetTools& AssetTools=FModuleManager::LoadModuleChecked<FAssetToolsModule>(TEXT("AssetTools")).Get();TArray<FString> Candidates;IFileManager::Get().FindFilesRecursive(Candidates,*FPaths::Combine(FPaths::ProjectDir(),TEXT("ContentSource/Story")),TEXT("C*.json"),true,false,false);Candidates.Sort();TArray<FString> Contracts;TMap<FName,FName> MissionMaps;for(const FString& Candidate:Candidates){TSharedPtr<FJsonObject> Root;if(!DarkArisenStoryMaterialize::ReadJson(Candidate,Root))continue;const FString Mission=DarkArisenStoryMaterialize::Str(Root,TEXT("missionId"));const FString Map=DarkArisenStoryMaterialize::Str(Root,TEXT("mapId"));if(Mission.IsEmpty()||Map.IsEmpty())continue;Contracts.Add(Candidate);MissionMaps.Add(FName(*Mission),FName(*Map));}if(Contracts.IsEmpty())return 3;int32 Failures=0;for(const FString& Contract:Contracts)if(!DarkArisenStoryMaterialize::MaterializeStoryContract(AssetTools,Contract,MissionMaps)){++Failures;UE_LOG(LogTemp,Error,TEXT("Story materialisation failed: %s"),*Contract);}if(!DarkArisenStoryMaterialize::MaterializeCredits()){++Failures;UE_LOG(LogTemp,Error,TEXT("Credits materialisation failed"));}return Failures==0?0:4;}
