[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Engine/Maps/Entry
GameDefaultMap=/Engine/Maps/Entry
ServerDefaultMap=/Engine/Maps/Entry
GlobalDefaultGameMode=/Script/DarkArisen.GreyboxGameMode

[/Script/Engine.Engine]
bSmoothFrameRate=False
bUseFixedFrameRate=False

[/Script/Engine.RendererSettings]
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Lumen.HardwareRayTracing=True
r.RayTracing=True
r.PathTracing=True
r.SkinCache.CompileShaders=True
r.RayTracing.UseTextureLod=True
r.Nanite.ProjectEnabled=True
r.Shadow.Virtual.Enable=1

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
-D3D12TargetedShaderFormats=PCD3D_SM5
+D3D12TargetedShaderFormats=PCD3D_SM6
Compiler=Default

[SystemSettings]
t.MaxFPS=60
r.VSync=1
r.DynamicRes.OperationMode=0
r.MotionBlurQuality=0
; Gameplay defaults to the real-time renderer. Path tracing is an explicit cinematic/preview mode.
r.RayTracing.EnableOnDemand=1
r.RayTracing.Enable=1

[/Script/Engine.GarbageCollectionSettings]
gc.CreateGCClusters=True
