// Copyright (c) 2026 Dark Arisen. All Rights Reserved.
#include "JakeCharacter.h"
#include "Animation/AnimInstance.h"
#include "Animation/AnimMontage.h"
#include "Camera/CameraComponent.h"
#include "Components/CameraStateComponent.h"
#include "Components/CapsuleComponent.h"
#include "Components/CombatComponent.h"
#include "Components/HealthComponent.h"
#include "Components/HeatExposureComponent.h"
#include "Components/InputComponent.h"
#include "Components/InteractionComponent.h"
#include "Components/LockOnComponent.h"
#include "Components/QuestJournalComponent.h"
#include "Components/StaminaComponent.h"
#include "Components/WaterBreathComponent.h"
#include "DarkArisen.h"
#include "Engine/Engine.h"
#include "Engine/GameViewportClient.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "GameFramework/PlayerController.h"
#include "GameFramework/SpringArmComponent.h"
#include "Missions/RexaM2MissionCatalog.h"
#include "Story/RacheStoryUnlockComponent.h"
#include "Systems/ProgressionEconomyComponent.h"
#include "UnrealClient.h"
AJakeCharacter::AJakeCharacter(){PrimaryActorTick.bCanEverTick=true;GetCapsuleComponent()->InitCapsuleSize(42,96);bUseControllerRotationPitch=false;bUseControllerRotationYaw=false;bUseControllerRotationRoll=false;auto* M=GetCharacterMovement();M->bOrientRotationToMovement=true;M->RotationRate=FRotator(0,360,0);M->JumpZVelocity=520;M->AirControl=.25f;M->MaxWalkSpeed=RunSpeedCentimetresPerSecond;M->BrakingDecelerationWalking=1400;HealthComponent=CreateDefaultSubobject<UHealthComponent>(TEXT("HealthComponent"));HealthComponent->bRallyEnabled=true;StaminaComponent=CreateDefaultSubobject<UStaminaComponent>(TEXT("StaminaComponent"));CombatComponent=CreateDefaultSubobject<UCombatComponent>(TEXT("CombatComponent"));WoundStateComponent=CreateDefaultSubobject<UWoundStateComponent>(TEXT("WoundStateComponent"));CameraStateComponent=CreateDefaultSubobject<UCameraStateComponent>(TEXT("CameraStateComponent"));InteractionComponent=CreateDefaultSubobject<UInteractionComponent>(TEXT("InteractionComponent"));LockOnComponent=CreateDefaultSubobject<ULockOnComponent>(TEXT("LockOnComponent"));QuestJournalComponent=CreateDefaultSubobject<UQuestJournalComponent>(TEXT("QuestJournalComponent"));HeatExposureComponent=CreateDefaultSubobject<UHeatExposureComponent>(TEXT("HeatExposureComponent"));WaterBreathComponent=CreateDefaultSubobject<UWaterBreathComponent>(TEXT("WaterBreathComponent"));ProgressionEconomyComponent=CreateDefaultSubobject<UProgressionEconomyComponent>(TEXT("ProgressionEconomyComponent"));RacheStoryUnlockComponent=CreateDefaultSubobject<URacheStoryUnlockComponent>(TEXT("RacheStoryUnlockComponent"));CameraBoom=CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));CameraBoom->SetupAttachment(RootComponent);CameraBoom->TargetArmLength=360;CameraBoom->SocketOffset=BaseCameraSocketOffset;CameraBoom->bUsePawnControlRotation=true;FollowCamera=CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));FollowCamera->SetupAttachment(CameraBoom,USpringArmComponent::SocketName);FollowCamera->bUsePawnControlRotation=false;}
void AJakeCharacter::BeginPlay(){Super::BeginPlay();if(!URexaM2MissionCatalog::RegisterAuthoredMissions(QuestJournalComponent))UE_LOG(LogDarkArisen,Error,TEXT("The authored Rexa M2 mission catalog failed closed."));HealthComponent->OnDied.AddDynamic(this,&AJakeCharacter::OnCharacterDied);StaminaComponent->OnStaminaDepleted.AddDynamic(this,&AJakeCharacter::OnStaminaDepleted);WoundStateComponent->OnWoundLayerChanged.AddDynamic(this,&AJakeCharacter::OnWoundLayerChanged);ApplyWoundLocomotion();}
void AJakeCharacter::Tick(float D){Super::Tick(D);UpdateWoundPresentation(D);if(!TouchMovement.IsNearlyZero()){MoveForward(TouchMovement.X);MoveRight(TouchMovement.Y);}}
void AJakeCharacter::SetupPlayerInputComponent(UInputComponent* I){check(I);Super::SetupPlayerInputComponent(I);I->BindAxis(TEXT("MoveForward"),this,&AJakeCharacter::MoveForward);I->BindAxis(TEXT("MoveRight"),this,&AJakeCharacter::MoveRight);I->BindAxis(TEXT("Turn"),this,&AJakeCharacter::Turn);I->BindAxis(TEXT("LookUp"),this,&AJakeCharacter::LookUp);I->BindAxis(TEXT("TurnRate"),this,&AJakeCharacter::TurnAtRate);I->BindAxis(TEXT("LookUpRate"),this,&AJakeCharacter::LookUpAtRate);I->BindAction(TEXT("Jump"),IE_Pressed,this,&AJakeCharacter::StartJump);I->BindAction(TEXT("Jump"),IE_Released,this,&AJakeCharacter::StopJump);I->BindAction(TEXT("Sprint"),IE_Pressed,this,&AJakeCharacter::StartSprint);I->BindAction(TEXT("Sprint"),IE_Released,this,&AJakeCharacter::StopSprint);I->BindAction(TEXT("LightAttack"),IE_Pressed,this,&AJakeCharacter::PerformLightAttack);I->BindAction(TEXT("HeavyAttack"),IE_Pressed,this,&AJakeCharacter::PerformHeavyAttack);I->BindAction(TEXT("Parry"),IE_Pressed,this,&AJakeCharacter::PerformParry);I->BindAction(TEXT("Dodge"),IE_Pressed,this,&AJakeCharacter::PerformDodge);I->BindAction(TEXT("Interact"),IE_Pressed,this,&AJakeCharacter::TryInteract);I->BindAction(TEXT("LockOn"),IE_Pressed,this,&AJakeCharacter::ToggleLockOn);I->BindAction(TEXT("Rache"),IE_Pressed,this,&AJakeCharacter::TryActivateRache);I->BindTouch(IE_Pressed,this,&AJakeCharacter::TouchStarted);I->BindTouch(IE_Repeat,this,&AJakeCharacter::TouchMoved);I->BindTouch(IE_Released,this,&AJakeCharacter::TouchStopped);}
float AJakeCharacter::TakeDamage(float A,const FDamageEvent& E,AController* C,AActor* D){const float Applied=Super::TakeDamage(A,E,C,D);HealthComponent->ApplyDamage(Applied,D);if(Applied>0)InteractionComponent->CancelActiveInteraction();return Applied;}
bool AJakeCharacter::RestoreAtCheckpoint(const FTransform& T){auto* PC=Cast<APlayerController>(GetController());if(!HealthComponent||!StaminaComponent||!CombatComponent||!CameraStateComponent||!WaterBreathComponent||!GetCharacterMovement())return false;StopSprint();LockOnComponent->ReleaseTarget();InteractionComponent->CancelActiveInteraction();GetCharacterMovement()->StopMovementImmediately();if(!SetActorTransform(T,false,nullptr,ETeleportType::TeleportPhysics))return false;HealthComponent->ResetForRespawn();StaminaComponent->ResetForRespawn();CombatComponent->ResetAfterRespawn();WaterBreathComponent->ResetForRespawn();CameraStateComponent->ReleaseToFree();GetCharacterMovement()->SetMovementMode(MOVE_Walking);ApplyWoundLocomotion();if(PC)EnableInput(PC);return true;}
void AJakeCharacter::MoveForward(float V){if(!Controller||FMath::IsNearlyZero(V)||HealthComponent->IsDead()||!CameraStateComponent->AllowsMoveInput())return;InteractionComponent->CancelActiveInteraction();AddMovementInput(FRotationMatrix(FRotator(0,Controller->GetControlRotation().Yaw,0)).GetUnitAxis(EAxis::X),V);}void AJakeCharacter::MoveRight(float V){if(!Controller||FMath::IsNearlyZero(V)||HealthComponent->IsDead()||!CameraStateComponent->AllowsMoveInput())return;InteractionComponent->CancelActiveInteraction();AddMovementInput(FRotationMatrix(FRotator(0,Controller->GetControlRotation().Yaw,0)).GetUnitAxis(EAxis::Y),V);}void AJakeCharacter::Turn(float V){if(CameraStateComponent->AllowsLookInput())AddControllerYawInput(V);}void AJakeCharacter::LookUp(float V){if(CameraStateComponent->AllowsLookInput())AddControllerPitchInput(V);}void AJakeCharacter::TurnAtRate(float R){if(CameraStateComponent->AllowsLookInput())AddControllerYawInput(R*BaseTurnRate*GetWorld()->GetDeltaSeconds());}void AJakeCharacter::LookUpAtRate(float R){if(CameraStateComponent->AllowsLookInput())AddControllerPitchInput(R*BaseLookUpRate*GetWorld()->GetDeltaSeconds());}
void AJakeCharacter::StartSprint(){if(const auto* PC=Cast<APlayerController>(GetController()))if(PC->IsInputKeyDown(EKeys::Gamepad_RightThumbstick)){TryActivateRache();return;}if(!HealthComponent->IsDead()&&StaminaComponent->CurrentStamina>0&&WoundStateComponent->IsSprintAllowed()&&CombatComponent->CurrentState==ECombatState::Idle&&!InteractionComponent->IsInteracting()){StaminaComponent->SetSprinting(true);ApplyWoundLocomotion();}}void AJakeCharacter::StopSprint(){StaminaComponent->SetSprinting(false);ApplyWoundLocomotion();}void AJakeCharacter::StartJump(){if(!HealthComponent->IsDead()&&CameraStateComponent->AllowsMoveInput()&&CombatComponent->CurrentState==ECombatState::Idle&&!InteractionComponent->IsInteracting()&&StaminaComponent->ConsumeStamina(12))Jump();}void AJakeCharacter::StopJump(){StopJumping();}
void AJakeCharacter::PerformLightAttack(){if(HealthComponent->IsDead()||InteractionComponent->IsInteracting()||!CombatComponent->PerformLightAttack())return;if(TryPlayActionMontage(LightAttackMontage))CombatComponent->RouteQueuedMeleeHitToAnimationNotify();}void AJakeCharacter::PerformHeavyAttack(){if(HealthComponent->IsDead()||InteractionComponent->IsInteracting()||!CombatComponent->PerformHeavyAttack())return;if(TryPlayActionMontage(HeavyAttackMontage))CombatComponent->RouteQueuedMeleeHitToAnimationNotify();}void AJakeCharacter::PerformParry(){if(!HealthComponent->IsDead()&&!InteractionComponent->IsInteracting()&&CombatComponent->PerformParry())TryPlayActionMontage(ParryMontage);}void AJakeCharacter::PerformDodge(){if(HealthComponent->IsDead()||InteractionComponent->IsInteracting())return;const FVector D=GetLastMovementInputVector().GetSafeNormal();if(CombatComponent->PerformDodge(D))TryPlayActionMontage(D.IsNearlyZero()?BackstepMontage:DodgeMontage);}void AJakeCharacter::TryInteract(){if(!HealthComponent->IsDead()&&CombatComponent->CurrentState==ECombatState::Idle&&CameraStateComponent->CurrentMode!=EPlayerCameraMode::Authored)InteractionComponent->TryBeginInteraction();}void AJakeCharacter::ToggleLockOn(){if(const auto* PC=Cast<APlayerController>(GetController()))if(PC->IsInputKeyDown(EKeys::Gamepad_LeftThumbstick)){TryActivateRache();return;}if(!HealthComponent->IsDead()&&CameraStateComponent->CurrentMode==EPlayerCameraMode::Free)LockOnComponent->ToggleLockOn();}void AJakeCharacter::TryActivateRache(){if(HealthComponent->IsDead()||InteractionComponent->IsInteracting()||CameraStateComponent->CurrentMode!=EPlayerCameraMode::Free)return;StopSprint();CombatComponent->StartRache();}
bool AJakeCharacter::TryPlayActionMontage(UAnimMontage* M){if(!M||!GetMesh())return false;auto* A=GetMesh()->GetAnimInstance();return A&&A->Montage_Play(M)>0;}void AJakeCharacter::UpdateWoundPresentation(float D){const float I=CameraStateComponent->WoundInstabilityAlpha;WoundCameraPhase+=D;const float A=MaximumWoundCameraDriftCentimetres*I;CameraBoom->SocketOffset=BaseCameraSocketOffset+FVector(FMath::Sin(WoundCameraPhase*2.1f)*A*.35f,FMath::Sin(WoundCameraPhase*1.3f)*A,FMath::Sin(WoundCameraPhase*.8f)*A*.55f);}void AJakeCharacter::ApplyWoundLocomotion(){const auto P=WoundStateComponent->GetPresentationProfile();GetCharacterMovement()->MaxWalkSpeed=(StaminaComponent->IsSprinting()?SprintSpeedCentimetresPerSecond:RunSpeedCentimetresPerSecond)*P.MovementSpeedScale;}
void AJakeCharacter::TouchStarted(ETouchIndex::Type F,FVector L){FVector2D S(1920,1080);if(GEngine&&GEngine->GameViewport&&GEngine->GameViewport->Viewport){auto Z=GEngine->GameViewport->Viewport->GetSizeXY();S=FVector2D(Z.X,Z.Y);}FTouchState T;T.Start=FVector2D(L.X,L.Y);T.Last=T.Start;T.bMovementZone=L.X<S.X*.5f&&!MovementTouch.IsSet();ActiveTouches.Add(F,T);if(T.bMovementZone)MovementTouch=F;}void AJakeCharacter::TouchMoved(ETouchIndex::Type F,FVector L){auto* T=ActiveTouches.Find(F);if(!T)return;FVector2D C(L.X,L.Y);if(T->bMovementZone){FVector2D D=(C-T->Start)/120.f;TouchMovement.X=FMath::Clamp(-D.Y,-1.f,1.f);TouchMovement.Y=FMath::Clamp(D.X,-1.f,1.f);}else{FVector2D D=C-T->Last;Turn(D.X*TouchLookSensitivity);LookUp(D.Y*TouchLookSensitivity);}T->Last=C;}void AJakeCharacter::TouchStopped(ETouchIndex::Type F,FVector){if(MovementTouch.IsSet()&&MovementTouch.GetValue()==F){TouchMovement=FVector2D::ZeroVector;MovementTouch.Reset();}ActiveTouches.Remove(F);}void AJakeCharacter::OnCharacterDied(AActor*){StopSprint();LockOnComponent->ReleaseTarget();InteractionComponent->CancelActiveInteraction();CombatComponent->SetDead();CameraStateComponent->ReleaseToFree();GetCharacterMovement()->DisableMovement();if(auto* PC=Cast<APlayerController>(GetController()))DisableInput(PC);}void AJakeCharacter::OnStaminaDepleted(){StopSprint();}void AJakeCharacter::OnWoundLayerChanged(EWoundLayer,EWoundLayer){ApplyWoundLocomotion();}
