// Copyright (c) 2026 Dark Arisen. All Rights Reserved.
#pragma once
#include "CoreMinimal.h"
#include "Components/WoundStateComponent.h"
#include "GameFramework/Character.h"
#include "InputCoreTypes.h"
#include "JakeCharacter.generated.h"
class UCameraComponent;class UCameraStateComponent;class UCombatComponent;class UHealthComponent;class UHeatExposureComponent;class UInteractionComponent;class ULockOnComponent;class UAnimMontage;class UProgressionEconomyComponent;class UQuestJournalComponent;class URacheStoryUnlockComponent;class USpringArmComponent;class UStaminaComponent;class UWaterBreathComponent;
UCLASS() class DARKARISEN_API AJakeCharacter:public ACharacter
{
GENERATED_BODY()
public:AJakeCharacter();virtual void BeginPlay() override;virtual void Tick(float DeltaSeconds) override;virtual void SetupPlayerInputComponent(UInputComponent* PlayerInputComponent) override;virtual float TakeDamage(float DamageAmount,const FDamageEvent& DamageEvent,AController* EventInstigator,AActor* DamageCauser) override;UFUNCTION(BlueprintCallable,Category="Jake|Persistence") bool RestoreAtCheckpoint(const FTransform& SpawnTransform);
UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UHealthComponent> HealthComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UStaminaComponent> StaminaComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UCombatComponent> CombatComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UWoundStateComponent> WoundStateComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UCameraStateComponent> CameraStateComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UInteractionComponent> InteractionComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<ULockOnComponent> LockOnComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UQuestJournalComponent> QuestJournalComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UHeatExposureComponent> HeatExposureComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UWaterBreathComponent> WaterBreathComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<UProgressionEconomyComponent> ProgressionEconomyComponent;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Components") TObjectPtr<URacheStoryUnlockComponent> RacheStoryUnlockComponent;
protected:UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Camera") TObjectPtr<USpringArmComponent> CameraBoom;UPROPERTY(VisibleAnywhere,BlueprintReadOnly,Category="Jake|Camera") TObjectPtr<UCameraComponent> FollowCamera;UPROPERTY(EditDefaultsOnly,BlueprintReadOnly,Category="Jake|Animation") TObjectPtr<UAnimMontage> LightAttackMontage;UPROPERTY(EditDefaultsOnly,BlueprintReadOnly,Category="Jake|Animation") TObjectPtr<UAnimMontage> HeavyAttackMontage;UPROPERTY(EditDefaultsOnly,BlueprintReadOnly,Category="Jake|Animation") TObjectPtr<UAnimMontage> ParryMontage;UPROPERTY(EditDefaultsOnly,BlueprintReadOnly,Category="Jake|Animation") TObjectPtr<UAnimMontage> DodgeMontage;UPROPERTY(EditDefaultsOnly,BlueprintReadOnly,Category="Jake|Animation") TObjectPtr<UAnimMontage> BackstepMontage;
private:struct FTouchState{FVector2D Start=FVector2D::ZeroVector;FVector2D Last=FVector2D::ZeroVector;bool bMovementZone=false;};TMap<ETouchIndex::Type,FTouchState> ActiveTouches;FVector2D TouchMovement=FVector2D::ZeroVector;TOptional<ETouchIndex::Type> MovementTouch;float BaseTurnRate=45.f,BaseLookUpRate=45.f,TouchLookSensitivity=.12f,RunSpeedCentimetresPerSecond=330.f,SprintSpeedCentimetresPerSecond=600.f;FVector BaseCameraSocketOffset=FVector(0,45,70);float WoundCameraPhase=0.f;UPROPERTY(EditDefaultsOnly,Category="Jake|Camera",meta=(ClampMin="0.0")) float MaximumWoundCameraDriftCentimetres=3.f;void MoveForward(float);void MoveRight(float);void Turn(float);void LookUp(float);void TurnAtRate(float);void LookUpAtRate(float);void StartSprint();void StopSprint();void StartJump();void StopJump();void PerformLightAttack();void PerformHeavyAttack();void PerformParry();void PerformDodge();void TryInteract();void ToggleLockOn();void TryActivateRache();bool TryPlayActionMontage(UAnimMontage*);void UpdateWoundPresentation(float);void ApplyWoundLocomotion();void TouchStarted(ETouchIndex::Type,FVector);void TouchMoved(ETouchIndex::Type,FVector);void TouchStopped(ETouchIndex::Type,FVector);UFUNCTION() void OnCharacterDied(AActor*);UFUNCTION() void OnStaminaDepleted();UFUNCTION() void OnWoundLayerChanged(EWoundLayer,EWoundLayer);
};
